# Some common term to remember

1. corpus
2. Vocubulary
3. Document
4. Word

# Bag of words

In [1]:
import numpy as np
import pandas as pd

In [2]:
df = pd.DataFrame({"text":["people watch dswithbappy",
                         "dswithbappy watch dswithbappy",
                         "people write comment",
                          "dswithbappy write comment"],"output":[1,1,0,0]})

df

text  output
0       people watch dswithbappy       1
1  dswithbappy watch dswithbappy       1
2           people write comment       0
3      dswithbappy write comment       0

In [3]:
from sklearn.feature_extraction.text import CountVectorizer  # Package for Bag of words of embedding words
cv = CountVectorizer()

In [4]:
bow = cv.fit_transform(df['text'])

In [5]:
#vocabulary
print(cv.vocabulary_)  # its give no. randomly to each unique word

{'people': 2, 'watch': 3, 'dswithbappy': 1, 'write': 4, 'comment': 0}


In [7]:
bow.toarray()  # it is going from vocubulary no. wise (0 to 4 here). Thats why in first text there is no comment so 0,
              # 1 is for dswithbappy so below dswithbappy there is 1 and for people and for watch 1

array([[0, 1, 1, 1, 0],
       [0, 2, 0, 1, 0],
       [1, 0, 1, 0, 1],
       [1, 1, 0, 0, 1]])

In [8]:
print(bow[0].toarray())
print(bow[1].toarray())
print(bow[2].toarray())   # checking row wise array form of word embedding to no.

[[0 1 1 1 0]]
[[0 2 0 1 0]]
[[1 0 1 0 1]]


In [9]:
# new
cv.transform(['Bappy watch dswithbappy']).toarray()

array([[0, 1, 0, 1, 0]])

In [11]:
# for training model we can take input and output colunm seperatly

X = bow.toarray()
y = df['output']

---------------------------

# N-grams

In [12]:
df = pd.DataFrame({"text":["people watch dswithbappy",
                         "dswithbappy watch dswithbappy",
                         "people write comment",
                          "dswithbappy write comment"],"output":[1,1,0,0]})

df

text  output
0       people watch dswithbappy       1
1  dswithbappy watch dswithbappy       1
2           people write comment       0
3      dswithbappy write comment       0

In [14]:
# BI grams
from sklearn.feature_extraction.text import CountVectorizer
cv = CountVectorizer(ngram_range=(2,2))  # It is type of Bag of words but here are using 2X2 matrix to two text at a time embedding uniquely
                                         # If we take 3X3 then it will take 3 words at a time and so on...

In [15]:
bow = cv.fit_transform(df['text'])

In [16]:
print(cv.vocabulary_)

{'people watch': 2, 'watch dswithbappy': 4, 'dswithbappy watch': 0, 'people write': 3, 'write comment': 5, 'dswithbappy write': 1}


In [17]:
print(bow[0].toarray())
print(bow[1].toarray())
print(bow[2].toarray())

[[0 0 1 0 1 0]]
[[1 0 0 0 1 0]]
[[0 0 0 1 0 1]]


In [18]:
#Ti gram
from sklearn.feature_extraction.text import CountVectorizer
cv = CountVectorizer(ngram_range=(3,3))

In [19]:
bow = cv.fit_transform(df['text'])

In [20]:
print(cv.vocabulary_)  # Like this

{'people watch dswithbappy': 2, 'dswithbappy watch dswithbappy': 0, 'people write comment': 3, 'dswithbappy write comment': 1}


In [21]:
print(bow[0].toarray())
print(bow[1].toarray())
print(bow[2].toarray())

[[0 0 1 0]]
[[1 0 0 0]]
[[0 0 0 1]]


# TF-IDF (Term frequency- Inverse document frequency)

In [22]:
df = pd.DataFrame({"text":["people watch dswithbappy",
                         "dswithbappy watch dswithbappy",
                         "people write comment",
                          "dswithbappy write comment"],"output":[1,1,0,0]})

df

text  output
0       people watch dswithbappy       1
1  dswithbappy watch dswithbappy       1
2           people write comment       0
3      dswithbappy write comment       0

In [23]:
from sklearn.feature_extraction.text import TfidfVectorizer
tfid= TfidfVectorizer()

In [24]:
arr = tfid.fit_transform(df['text']).toarray()

In [25]:
arr

array([[0.        , 0.49681612, 0.61366674, 0.61366674, 0.        ],
       [0.        , 0.8508161 , 0.        , 0.52546357, 0.        ],
       [0.57735027, 0.        , 0.57735027, 0.        , 0.57735027],
       [0.61366674, 0.49681612, 0.        , 0.        , 0.61366674]])

 1. Term Frequency (TF): This measures how often a particular word appears in a specific document. The higher the TF, the more relevant the word is to that document.

2. Inverse Document Frequency (IDF): This measures how frequently a word appears across the entire document collection. The less frequent a word is, the more informative it is considered, as it might be specific to the topic or context of the document.

TF-IDF assigns a higher weight to words that appear frequently in a specific document but less frequently overall. This helps identify words that are more relevant and discriminative for that document compared to the rest of the corpus.

In [26]:
print(tfid.idf_)  # As per the formula of TF IDF here we are getting idf value of TF IDF

[1.51082562 1.22314355 1.51082562 1.51082562 1.51082562]
